"""
Resolves and verifies model sources on Hugging Face Hub for Turbo-WinFare Dense.
Outputs docs/MODEL_SOURCES.md and provides --check verification.
"""

import argparse
import json
import sys
import urllib.request
import urllib.parse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

UA = {"User-Agent": "turbo-dense-model-resolver"}

PINNED_MODELS = {
    "target_31b_mlx": {
        "repo_id": "mlx-community/gemma-4-31b-it-4bit",
        "pinned_sha": "696d436c404745a59f30e4939a658162b0a9e57f",
        "format": "MLX Affine INT4 (group_size=64)",
        "expected_files": [
            "model-00001-of-00004.safetensors",
            "model-00002-of-00004.safetensors",
            "model-00003-of-00004.safetensors",
            "model-00004-of-00004.safetensors",
            "config.json",
            "model.safetensors.index.json",
            "tokenizer.json",
            "tokenizer_config.json"
        ]
    },
    "draft_e2b_mlx": {
        "repo_id": "mlx-community/gemma-4-e2b-it-4bit",
        "pinned_sha": "238767527555cb75a05732a84dff5d6ba0dd6809",
        "format": "MLX Affine INT4 (group_size=64)",
        "expected_files": [
            "model.safetensors",
            "config.json",
            "tokenizer.json",
            "tokenizer_config.json"
        ]
    }
}


def fetch_json(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read().decode())


def fetch_file_size(repo_id, rfilename):
    url = f"https://huggingface.co/{repo_id}/resolve/main/{rfilename}"
    req = urllib.request.Request(url, headers=UA, method="HEAD")
    with urllib.request.urlopen(req, timeout=15) as resp:
        return int(resp.headers.get("Content-Length", 0))


def resolve_models():
    results = {}
    for key, info in PINNED_MODELS.items():
        repo_id = info["repo_id"]
        print(f"Resolving {repo_id}...")
        api_data = fetch_json(f"https://huggingface.co/api/models/{repo_id}")
        sha = api_data.get("sha")
        siblings = {s["rfilename"]: s for s in api_data.get("siblings", [])}

        file_sizes = {}
        total_bytes = 0
        for fname in info["expected_files"]:
            if fname in siblings:
                size = fetch_file_size(repo_id, fname)
                file_sizes[fname] = size
                total_bytes += size
            else:
                raise RuntimeError(f"Missing expected file {fname} in {repo_id}")

        config_data = fetch_json(f"https://huggingface.co/{repo_id}/raw/main/config.json")
        text_cfg = config_data.get("text_config", config_data)

        results[key] = {
            "repo_id": repo_id,
            "pinned_sha": sha,
            "format": info["format"],
            "total_bytes": total_bytes,
            "file_sizes": file_sizes,
            "text_config": {
                "hidden_size": text_cfg.get("hidden_size"),
                "intermediate_size": text_cfg.get("intermediate_size"),
                "num_hidden_layers": text_cfg.get("num_hidden_layers"),
                "num_attention_heads": text_cfg.get("num_attention_heads"),
                "num_key_value_heads": text_cfg.get("num_key_value_heads"),
                "head_dim": text_cfg.get("head_dim"),
                "hidden_activation": text_cfg.get("hidden_activation"),
                "sliding_window": text_cfg.get("sliding_window"),
                "vocab_size": text_cfg.get("vocab_size"),
                "final_logit_softcapping": text_cfg.get("final_logit_softcapping")
            }
        }
    return results


def write_markdown(results, out_path):
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Model Sources & Verified Checkpoints\n\n")
        f.write("**Date:** 2026-08-29  \n")
        f.write("**Generated by:** `tools/resolve_model.py`  \n\n")

        f.write("## 1. Primary Checkpoints\n\n")
        for key, res in results.items():
            f.write(f"### {res['repo_id']}\n\n")
            f.write(f"- **Role:** {'Target 31B Dense Model' if '31b' in key else 'Draft E2B Model'}\n")
            f.write(f"- **Pinned Revision (SHA):** `{res['pinned_sha']}`\n")
            f.write(f"- **Quantization Format:** `{res['format']}`\n")
            f.write(f"- **Total Weights Payload:** {res['total_bytes']:,} bytes ({res['total_bytes'] / (1024**3):.2f} GiB)\n")
            f.write("- **Model Geometry:**\n")
            tc = res["text_config"]
            f.write(f"  - `d_model`: {tc['hidden_size']}, `d_ff`: {tc['intermediate_size']}\n")
            f.write(f"  - `num_layers`: {tc['num_hidden_layers']} blocks\n")
            f.write(f"  - Heads: {tc['num_attention_heads']} Query / {tc['num_key_value_heads']} KV (head_dim={tc['head_dim']})\n")
            f.write(f"  - Activation: `{tc['hidden_activation']}`\n")
            f.write(f"  - Sliding Window: {tc['sliding_window']}\n")
            f.write(f"  - Vocab Size: {tc['vocab_size']}\n")
            f.write(f"  - Logit Softcapping: {tc['final_logit_softcapping']}\n\n")
            f.write("#### Verified File List:\n\n")
            f.write("| File | Size (Bytes) | Size (GiB) |\n")
            f.write("|---|---:|---:|\n")
            for fname, sz in res["file_sizes"].items():
                f.write(f"| `{fname}` | {sz:,} B | {sz / (1024**3):.2f} GiB |\n")
            f.write("\n")

        f.write("## 2. Converter Ingestion Formats\n\n")
        f.write("The converter `tools/convert_hf_to_g4dense.py` is configured to ingest:\n\n")
        f.write("1. **MLX Affine INT4 (Group Size 64)** (*Primary*):\n")
        f.write("   - Weights: `uint32` packed nibbles (low-nibble-first, 8 weights per `uint32`).\n")
        f.write("   - Scales: `float16` / `bfloat16` per group of 64 elements.\n")
        f.write("   - Biases: `float16` / `bfloat16` per group of 64 elements.\n")
        f.write("   - Formula: `w = q * scale + bias`.\n\n")
        f.write("2. **QAT W4A16 / AWQ INT4 Group-64** (*Secondary*):\n")
        f.write("   - Ingests symmetric/asymmetric scales and zeros.\n\n")
        f.write("3. **GGUF Q4_K_M / Q4_0** (*Supported via GGUF unpacker*).\n")


def check_models():
    print("Checking Hugging Face model sources and pinned revisions...")
    for key, info in PINNED_MODELS.items():
        repo_id = info["repo_id"]
        expected_sha = info["pinned_sha"]
        api_data = fetch_json(f"https://huggingface.co/api/models/{repo_id}")
        sha = api_data.get("sha")
        print(f"[{key}] {repo_id}: SHA = {sha}")
        if sha != expected_sha:
            print(f"Warning: SHA mismatch for {repo_id}: expected {expected_sha}, got {sha}")
        siblings = {s["rfilename"]: s for s in api_data.get("siblings", [])}
        for fname in info["expected_files"]:
            if fname not in siblings:
                print(f"ERROR: {fname} missing in {repo_id}")
                return False
    print("CHECK PASSED: All model sources and files match Hugging Face Hub.")
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify model sources match Hub API")
    ap.add_argument("--out", default="docs/MODEL_SOURCES.md", help="output markdown path")
    args = ap.parse_args()

    if args.check:
        ok = check_models()
        return 0 if ok else 1

    results = resolve_models()
    write_markdown(results, args.out)
    print(f"Wrote {args.out}")

    if not check_models():
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
